version: 2

sources:
  - name: pc
    schema: Steam_data
    tables:
      - name: steam
        identifier: steam_data
        description: Pc games data

  - name: Steam_data
    schema: dbt_jr
    tables:
      - name: metacritic_score
        description: Count of games under % category review score

  - name: sales_data
    schema: video_games_data
    tables:

      - name: sales
        identifier: video_games_data
        description: The sales data (copies in millions)
        

  - name: igdb
    schema: igdb_data
    tables:

      - name: main
        identifier: data_200K
        description: main dataset with multi-platform reviews
        columns:
          - name: id
            description: the primary key of this table
            tests:
              - unique
              - not_null
        

      - name: categories
        identifier: category_mapping
        description: A map of the different categories of games

        columns:
          - name: category
            description: the primary key of this table
            tests:
              - unique
              - not_null

      
      
      - name: company
        identifier: companies
        description: A map of the companies in the involved companies dataset
        
        columns:
          - name: id
            description: the primary key of this table
            tests:
              - unique
              - not_null


      - name: involved_company
        identifier: involved_companies
        description: A map of the publishers and developers

        columns:
          - name: id
            description: the primary key of this table
            tests:
              - unique
              - not_null

      - name: genre
        identifier: genres
        description: A map of the genres

        columns:
          - name: id
            description: the primary key of this table
            tests:
              - unique
              - not_null

      - name: platforms
        description: a map of the platforms

        columns:
          - name: id
            description: the primary key of this table
            tests:
              - unique
              - not_null

      - name: perspective
        identifier: player_perspectives
        description: player perspective map

        columns:
          - name: id
            description: the primary key of this table
            tests:
              - unique
              - not_null

      - name: themes
        description: a map of the themes

        columns:
          - name: id
            description: the primary key of this table
            tests:
              - unique
              - not_null
      
      - name: game_modes
        description: a map of the game modes

        columns:
          - name: id
            description: the primary key of this table
            tests:
              - unique
              - not_null
      
      - name: franchise
        description: a map of the franchise the game belongs to

        columns:
          - name: id
            description: the primary key of this table
            tests:
              - unique
              - not_null

  - name: mart
    schema: Final_mart
    tables:
      - name: main_game_modes
        description: game modes table
      - name: main_genre
        description: genre table
      - name: main_platforms
        description: platforms table
      - name: main_theme
        description: themes table