version: 2

sources:
  - name: pc
    schema: Steam_data
    tables:
      - name: steam
        identifier: steam_data
        description: Pc games data



  - name: sales_data
    schema: video_games_data
    tables:

      - name: sales
        identifier: video_games_data
        description: The sales data (copies in millions)
        

  - name: igdb
    schema: igdb_data
    tables:

      - name: main
        identifier: data_200K
        description: main dataset with multi-platform reviews
        

      - name: categories
        identifier: category_mapping
        description: A map of the different categories of games

      
      
      - name: company
        identifier: companies
        description: A map of the companies in the involved companies dataset